name: Events Demo 1
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: |
          cd ..
          echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd 01\ Starting\ Project 
          npm ci
      - name: Test code
        run: |
          cd 01\ Starting\ Project 
          npm run test
      - name: Build code
        run: |
          cd 01\ Starting\ Project 
          npm run build
      - name: Deploy project
        run: echo "Deploying..."
