name: Test Project
on:
  push:
    branches:
      - test-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: |
          cd 02\ Starting\ Project/
          npm test
